/**
 * Name + location/year per archive photo. Filenames under
 * public/images/archive/ are themselves slugified from "Name - Location
 * Year" (e.g. "Sunset at the marina - Ibiza 2023.jpg" → this entry) — see
 * CLAUDE.md for the intake convention when adding new photos.
 */
export const archiveCaptions: Record<string, { name: string; location: string }> = {
  "/images/archive/abandoned-airport-italy-2021.jpg": { name: "Abandoned airport", location: "Italy 2021" },
  "/images/archive/bali-nusa-penida-2022.jpg": { name: "Bali", location: "Nusa Penida 2022" },
  "/images/archive/golden-hour-surfing-bali-2022.jpg": { name: "Golden hour surfing", location: "Bali 2022" },
  "/images/archive/winter-on-the-slopes-fiss-2022.jpg": { name: "Winter on the slopes", location: "Fiss 2022" },
  "/images/archive/kelingking-beach-nusa-penida-2022.jpg": { name: "Kelingking Beach", location: "Nusa Penida 2022" },
  "/images/archive/tropical-picknick-bali-2022.jpg": { name: "Tropical picknick", location: "Bali 2022" },
  "/images/archive/mountain-view-fiss-2022.jpg": { name: "Mountain view", location: "Fiss 2022" },
  "/images/archive/early-morning-in-the-mountains-fiss-2022.jpg": { name: "Early morning in the mountains", location: "Fiss 2022" },
  "/images/archive/collection-of-surfboards-bali-2022.jpg": { name: "Collection of surfboards", location: "Bali 2022" },
  "/images/archive/a-view-on-the-colosseum-italy-2021.jpg": { name: "A view on the colosseum", location: "Italy 2021" },
  "/images/archive/tropical-groceriestore-gili-islands-2022.jpg": { name: "Tropical groceriestore", location: "Gili islands 2022" },
  "/images/archive/the-perfect-holiday-spot-italy-2021.jpg": { name: "The perfect holiday spot", location: "Italy 2021" },
  "/images/archive/lifeguard-s-house-bali-2022.jpg": { name: "Lifeguard's house", location: "Bali 2022" },
  "/images/archive/bali-bali-2022.jpg": { name: "Bali", location: "Bali 2022" },
  "/images/archive/cinque-terre-italy-2021.jpg": { name: "Cinque Terre", location: "Italy 2021" },
  "/images/archive/colorful-mitsubishi-bali-2022.jpg": { name: "Colorful Mitsubishi", location: "Bali 2022" },
  "/images/archive/playing-football-in-paradise-gili-islands-2022.jpg": { name: "Playing football in paradise", location: "Gili islands 2022" },
  "/images/archive/parked-car-bali-2022.jpg": { name: "Parked car", location: "Bali 2022" },
  "/images/archive/classic-skilift-fiss-2022.jpg": { name: "Classic skilift", location: "Fiss 2022" },
  "/images/archive/cinque-terre-italy-2021-2.jpg": { name: "Cinque Terre", location: "Italy 2021" },
  "/images/archive/scooter-parking-bali-2022.jpg": { name: "Scooter parking", location: "Bali 2022" },
  "/images/archive/diamond-beach-nusa-penida-2022.jpg": { name: "Diamond beach", location: "Nusa Penida 2022" },
  "/images/archive/tegalalang-rice-terrace-bali-2022.jpg": { name: "Tegalalang rice terrace", location: "Bali 2022" },
  "/images/archive/tropical-gas-station-nusa-penida-2022.jpg": { name: "Tropical gas station", location: "Nusa Penida 2022" },
  "/images/archive/padang-padang-beach-bali-2022.jpg": { name: "Padang Padang beach", location: "Bali 2022" },
  "/images/archive/tower-of-pisa-italy-2021.jpg": { name: "Tower of Pisa", location: "Italy 2021" },
  "/images/archive/tropical-paradise-gili-islands-2022.jpg": { name: "Tropical paradise", location: "Gili islands 2022" },
  "/images/archive/sunrise-on-mount-batur-bali-2022.jpg": { name: "Sunrise on mount Batur", location: "Bali 2022" },
  "/images/archive/italian-porche-italy-2021.jpg": { name: "Italian Porche", location: "Italy 2021" },
  "/images/archive/chilling-on-the-beach-italy-2021.jpg": { name: "Chilling on the beach", location: "Italy 2021" },
  "/images/archive/surfing-in-black-white-bali-2022.jpg": { name: "Surfing in Black & White", location: "Bali 2022" },
  "/images/archive/winter-on-the-slopes-fiss-2022-2.jpg": { name: "Winter on the slopes", location: "Fiss 2022" },
  "/images/archive/golden-hour-surfing-bali-2022-2.jpg": { name: "Golden hour surfing", location: "Bali 2022" },
  "/images/archive/view-on-the-mountains-fiss-2022.jpg": { name: "View on the mountains", location: "Fiss 2022" },
  "/images/archive/a-view-on-lombok-gili-islands-2022.jpg": { name: "a view on Lombok", location: "Gili islands 2022" },
  "/images/archive/roadtrip-tuscany-italy-2021.jpg": { name: "Roadtrip Tuscany", location: "Italy 2021" },
  "/images/archive/diamond-beach-nusa-penida-2022-2.jpg": { name: "Diamond beach", location: "Nusa Penida 2022" },
  "/images/archive/golden-hour-surfing-bali-2022-3.jpg": { name: "Golden Hour Surfing", location: "Bali 2022" },
  "/images/archive/sea-fishing-saint-tropez-2020.jpg": { name: "Sea fishing", location: "Saint Tropez 2020" },
  "/images/archive/ameland-lighthouse-ameland-2021.jpg": { name: "Ameland lighthouse", location: "Ameland 2021" },
  "/images/archive/beach-bird-netherlands-2020.jpg": { name: "Beach bird", location: "Netherlands 2020" },
  "/images/archive/beach-houses-netherlands-2020.jpg": { name: "Beach houses", location: "Netherlands 2020" },
  "/images/archive/beach-houses-netherlands-2020-2.jpg": { name: "Beach houses", location: "Netherlands 2020" },
  "/images/archive/cadillac-in-the-rain-netherlands-2021.jpg": { name: "Cadillac in the rain", location: "Netherlands 2021" },
  "/images/archive/riviera-villa-cote-d-azur-2020.jpg": { name: "Riviera villa", location: "Côte d'Azur 2020" },
  "/images/archive/ice-skating-netherlands-2021.jpg": { name: "Ice skating", location: "Netherlands 2021" },
  "/images/archive/island-ferry-wadden-sea-2021.jpg": { name: "Island ferry", location: "Wadden Sea 2021" },
  "/images/archive/village-under-the-peak-dolomites-2022.jpg": { name: "Village under the peak", location: "Dolomites 2022" },
  "/images/archive/crossing-the-tracks-cape-town-2024.jpg": { name: "Crossing the tracks", location: "Cape Town 2024" },
  "/images/archive/golden-beach-cape-town-2024.jpg": { name: "Golden beach", location: "Cape Town 2024" },
  "/images/archive/green-point-stadium-cape-town-2024.jpg": { name: "Green Point stadium", location: "Cape Town 2024" },
  "/images/archive/retro-gas-station-cape-town-2024.jpg": { name: "Retro gas station", location: "Cape Town 2024" },
  "/images/archive/lion-s-head-cape-town-2024.jpg": { name: "Lion's Head", location: "Cape Town 2024" },
  "/images/archive/laundry-day-cape-town-2024.jpg": { name: "Laundry day", location: "Cape Town 2024" },
  "/images/archive/camp-below-the-peak-dolomites-2026.jpg": { name: "Camp below the peak", location: "Dolomites 2026" },
  "/images/archive/alpine-meadow-dolomites-2026.jpg": { name: "Alpine meadow", location: "Dolomites 2026" },
  "/images/archive/bikes-at-lago-di-braies-dolomites-2026.jpg": { name: "Bikes at Lago di Braies", location: "Dolomites 2026" },
  "/images/archive/silhouette-dolomites-2026.jpg": { name: "Silhouette", location: "Dolomites 2026" },
  "/images/archive/loaded-up-dolomites-2026.jpg": { name: "Loaded up", location: "Dolomites 2026" },
  "/images/archive/shadow-self-portrait-dolomites-2026.jpg": { name: "Shadow self-portrait", location: "Dolomites 2026" },
  "/images/archive/house-number-73-cape-town-2026.jpg": { name: "House number 73", location: "Cape Town 2026" },
  "/images/archive/beach-huts-cape-town-2026.jpg": { name: "Beach huts", location: "Cape Town 2026" },
  "/images/archive/wild-camping-dolomites-2026.jpg": { name: "Wild camping", location: "Dolomites 2026" },
  "/images/archive/mountain-marina-lake-garda-2026.jpg": { name: "Mountain marina", location: "Lake Garda 2026" },
  "/images/archive/room-with-a-view-dolomites-2026.jpg": { name: "Room with a view", location: "Dolomites 2026" },
  "/images/archive/lunch-break-dolomites-2026.jpg": { name: "Lunch break", location: "Dolomites 2026" },
  "/images/archive/ponto-final-lisbon-2026.jpg": { name: "Ponto Final", location: "Lisbon 2026" },
  "/images/archive/above-the-valley-dolomites-2026.jpg": { name: "Above the valley", location: "Dolomites 2026" },
  "/images/archive/wildflowers-dolomites-2026.jpg": { name: "Wildflowers", location: "Dolomites 2026" },
  "/images/archive/alpine-cows-dolomites-2026.jpg": { name: "Alpine cows", location: "Dolomites 2026" },
  "/images/archive/alpine-hotel-dolomites-2026.jpg": { name: "Alpine hotel", location: "Dolomites 2026" },
  "/images/archive/dusk-over-the-lake-lake-garda-2026.jpg": { name: "Dusk over the lake", location: "Lake Garda 2026" },
  "/images/archive/which-way-next-dolomites-2026.jpg": { name: "Which way next", location: "Dolomites 2026" },
  "/images/archive/pedal-boats-lake-garda-2026.jpg": { name: "Pedal boats", location: "Lake Garda 2026" },
  "/images/archive/golden-hour-bike-dolomites-2026.jpg": { name: "Golden hour bike", location: "Dolomites 2026" },
  "/images/archive/packed-and-ready-dolomites-2026.jpg": { name: "Packed and ready", location: "Dolomites 2026" },
  "/images/archive/marina-at-sunset-lake-garda-2026.jpg": { name: "Marina at sunset", location: "Lake Garda 2026" },
  "/images/archive/pastel-corner-dolomites-2026.jpg": { name: "Pastel corner", location: "Dolomites 2026" },
  "/images/archive/lakeside-hotel-lake-garda-2026.jpg": { name: "Lakeside hotel", location: "Lake Garda 2026" },
  "/images/archive/below-the-wall-dolomites-2026.jpg": { name: "Below the wall", location: "Dolomites 2026" },
  "/images/archive/view-from-the-tent-dolomites-2026.jpg": { name: "View from the tent", location: "Dolomites 2026" },
  "/images/archive/crossing-the-border-dolomites-2026.jpg": { name: "Crossing the border", location: "Dolomites 2026" },
  "/images/archive/church-in-the-vineyards-italy-2026.jpg": { name: "Church in the vineyards", location: "Italy 2026" },
  "/images/archive/nightfall-on-the-lake-lake-garda-2026.jpg": { name: "Nightfall on the lake", location: "Lake Garda 2026" },
  "/images/archive/lake-ferry-lake-garda-2026.jpg": { name: "Lake ferry", location: "Lake Garda 2026" },
  "/images/archive/chalet-country-alps-2026.jpg": { name: "Chalet country", location: "Alps 2026" },
  "/images/archive/through-the-trees-italy-2026.jpg": { name: "Through the trees", location: "Italy 2026" },
  "/images/archive/glittering-water-lake-garda-2026.jpg": { name: "Glittering water", location: "Lake Garda 2026" },
  "/images/archive/lago-di-braies-dolomites-2026.jpg": { name: "Lago di Braies", location: "Dolomites 2026" },
  "/images/archive/hilltop-church-dolomites-2026.jpg": { name: "Hilltop church", location: "Dolomites 2026" },
  "/images/archive/summer-chairlift-dolomites-2026.jpg": { name: "Summer chairlift", location: "Dolomites 2026" },
  "/images/archive/vintage-caravan-dolomites-2026.jpg": { name: "Vintage caravan", location: "Dolomites 2026" },
  "/images/archive/prinsentuin-leeuwarden-2020.jpg": { name: "Prinsentuin", location: "Leeuwarden 2020" },
  "/images/archive/prinsentuin-leeuwarden-2021.jpg": { name: "Prinsentuin", location: "Leeuwarden 2021" },
  "/images/archive/retro-bike-netherlands-2021.jpg": { name: "Retro bike", location: "Netherlands 2021" },
  "/images/archive/sunset-tower-netherlands-2021.jpg": { name: "Sunset tower", location: "Netherlands 2021" },
  "/images/archive/evening-sky-netherlands-2021.jpg": { name: "Evening sky", location: "Netherlands 2021" },
  "/images/archive/dune-cabin-terschelling-2020.jpg": { name: "Dune cabin", location: "Terschelling 2020" },
  "/images/archive/cycling-the-crete-tuscany-2021.jpg": { name: "Cycling the Crete", location: "Tuscany 2021" },
  "/images/archive/vintage-volvo-netherlands-2020.jpg": { name: "Vintage Volvo", location: "Netherlands 2020" },
  "/images/archive/vintage-volvo-netherlands-2020-2.jpg": { name: "Vintage Volvo", location: "Netherlands 2020" },
  "/images/archive/wadden-at-low-tide-wadden-sea-2021.jpg": { name: "Wadden at low tide", location: "Wadden Sea 2021" },
  "/images/archive/frozen-morning-netherlands-2021.jpg": { name: "Frozen morning", location: "Netherlands 2021" },
  "/images/archive/passo-sella-dolomites-2021.jpg": { name: "Passo Sella", location: "Dolomites 2021" },
  "/images/archive/autumn-in-the-harbour-netherlands-2021.jpg": { name: "Autumn in the harbour", location: "Netherlands 2021" },
  "/images/archive/caught-on-camera-netherlands-2021.jpg": { name: "Caught on camera", location: "Netherlands 2021" },
  "/images/archive/twin-doors-netherlands-2021.jpg": { name: "Twin doors", location: "Netherlands 2021" },
  "/images/archive/beach-post-netherlands-2021.jpg": { name: "Beach post", location: "Netherlands 2021" },
  "/images/archive/mailboxes-in-bloom-netherlands-2021.jpg": { name: "Mailboxes in bloom", location: "Netherlands 2021" },
  "/images/archive/green-jersey-netherlands-2026.jpg": { name: "Green jersey", location: "Netherlands 2026" },
  "/images/archive/polka-dot-jersey-netherlands-2026.jpg": { name: "Polka dot jersey", location: "Netherlands 2026" },
};
