/**
 * Name + location/year per moments photo. Filenames under
 * public/images/moments/ are themselves slugified from "Name - Location
 * Year" (e.g. "Sunset at the marina - Ibiza 2023.jpg" → this entry) — see
 * CLAUDE.md for the intake convention when adding new photos.
 */
export const momentsCaptions: Record<string, { name: string; location: string }> = {
  "/images/moments/abandoned-airport-italy-2021.jpg": { name: "Abandoned airport", location: "Italy 2021" },
  "/images/moments/bali-nusa-penida-2022.jpg": { name: "Bali", location: "Nusa Penida 2022" },
  "/images/moments/golden-hour-surfing-bali-2022.jpg": { name: "Golden hour surfing", location: "Bali 2022" },
  "/images/moments/winter-on-the-slopes-fiss-2022.jpg": { name: "Winter on the slopes", location: "Fiss 2022" },
  "/images/moments/kelingking-beach-nusa-penida-2022.jpg": { name: "Kelingking Beach", location: "Nusa Penida 2022" },
  "/images/moments/tropical-picknick-bali-2022.jpg": { name: "Tropical picknick", location: "Bali 2022" },
  "/images/moments/mountain-view-fiss-2022.jpg": { name: "Mountain view", location: "Fiss 2022" },
  "/images/moments/early-morning-in-the-mountains-fiss-2022.jpg": { name: "Early morning in the mountains", location: "Fiss 2022" },
  "/images/moments/collection-of-surfboards-bali-2022.jpg": { name: "Collection of surfboards", location: "Bali 2022" },
  "/images/moments/a-view-on-the-colosseum-italy-2021.jpg": { name: "A view on the colosseum", location: "Italy 2021" },
  "/images/moments/tropical-groceriestore-gili-islands-2022.jpg": { name: "Tropical groceriestore", location: "Gili islands 2022" },
  "/images/moments/the-perfect-holiday-spot-italy-2021.jpg": { name: "The perfect holiday spot", location: "Italy 2021" },
  "/images/moments/lifeguard-s-house-bali-2022.jpg": { name: "Lifeguard's house", location: "Bali 2022" },
  "/images/moments/bali-bali-2022.jpg": { name: "Bali", location: "Bali 2022" },
  "/images/moments/cinque-terre-italy-2021.jpg": { name: "Cinque Terre", location: "Italy 2021" },
  "/images/moments/colorful-mitsubishi-bali-2022.jpg": { name: "Colorful Mitsubishi", location: "Bali 2022" },
  "/images/moments/playing-football-in-paradise-gili-islands-2022.jpg": { name: "Playing football in paradise", location: "Gili islands 2022" },
  "/images/moments/parked-car-bali-2022.jpg": { name: "Parked car", location: "Bali 2022" },
  "/images/moments/classic-skilift-fiss-2022.jpg": { name: "Classic skilift", location: "Fiss 2022" },
  "/images/moments/cinque-terre-italy-2021-2.jpg": { name: "Cinque Terre", location: "Italy 2021" },
  "/images/moments/scooter-parking-bali-2022.jpg": { name: "Scooter parking", location: "Bali 2022" },
  "/images/moments/diamond-beach-nusa-penida-2022.jpg": { name: "Diamond beach", location: "Nusa Penida 2022" },
  "/images/moments/tegalalang-rice-terrace-bali-2022.jpg": { name: "Tegalalang rice terrace", location: "Bali 2022" },
  "/images/moments/tropical-gas-station-nusa-penida-2022.jpg": { name: "Tropical gas station", location: "Nusa Penida 2022" },
  "/images/moments/padang-padang-beach-bali-2022.jpg": { name: "Padang Padang beach", location: "Bali 2022" },
  "/images/moments/tower-of-pisa-italy-2021.jpg": { name: "Tower of Pisa", location: "Italy 2021" },
  "/images/moments/tropical-paradise-gili-islands-2022.jpg": { name: "Tropical paradise", location: "Gili islands 2022" },
  "/images/moments/sunrise-on-mount-batur-bali-2022.jpg": { name: "Sunrise on mount Batur", location: "Bali 2022" },
  "/images/moments/italian-porche-italy-2021.jpg": { name: "Italian Porche", location: "Italy 2021" },
  "/images/moments/chilling-on-the-beach-italy-2021.jpg": { name: "Chilling on the beach", location: "Italy 2021" },
  "/images/moments/surfing-in-black-white-bali-2022.jpg": { name: "Surfing in Black & White", location: "Bali 2022" },
  "/images/moments/winter-on-the-slopes-fiss-2022-2.jpg": { name: "Winter on the slopes", location: "Fiss 2022" },
  "/images/moments/golden-hour-surfing-bali-2022-2.jpg": { name: "Golden hour surfing", location: "Bali 2022" },
  "/images/moments/view-on-the-mountains-fiss-2022.jpg": { name: "View on the mountains", location: "Fiss 2022" },
  "/images/moments/a-view-on-lombok-gili-islands-2022.jpg": { name: "a view on Lombok", location: "Gili islands 2022" },
  "/images/moments/roadtrip-tuscany-italy-2021.jpg": { name: "Roadtrip Tuscany", location: "Italy 2021" },
  "/images/moments/diamond-beach-nusa-penida-2022-2.jpg": { name: "Diamond beach", location: "Nusa Penida 2022" },
  "/images/moments/golden-hour-surfing-bali-2022-3.jpg": { name: "Golden Hour Surfing", location: "Bali 2022" },
  "/images/moments/sea-fishing-saint-tropez-2020.jpg": { name: "Sea fishing", location: "Saint Tropez 2020" },
  "/images/moments/ameland-lighthouse-ameland-2021.jpg": { name: "Ameland lighthouse", location: "Ameland 2021" },
  "/images/moments/beach-bird-netherlands-2020.jpg": { name: "Beach bird", location: "Netherlands 2020" },
  "/images/moments/beach-houses-netherlands-2020.jpg": { name: "Beach houses", location: "Netherlands 2020" },
  "/images/moments/beach-houses-netherlands-2020-2.jpg": { name: "Beach houses", location: "Netherlands 2020" },
  "/images/moments/cadillac-in-the-rain-netherlands-2021.jpg": { name: "Cadillac in the rain", location: "Netherlands 2021" },
  "/images/moments/riviera-villa-cote-d-azur-2020.jpg": { name: "Riviera villa", location: "Côte d'Azur 2020" },
  "/images/moments/ice-skating-netherlands-2021.jpg": { name: "Ice skating", location: "Netherlands 2021" },
  "/images/moments/island-ferry-wadden-sea-2021.jpg": { name: "Island ferry", location: "Wadden Sea 2021" },
  "/images/moments/village-under-the-peak-dolomites-2022.jpg": { name: "Village under the peak", location: "Dolomites 2022" },
  "/images/moments/crossing-the-tracks-cape-town-2024.jpg": { name: "Crossing the tracks", location: "Cape Town 2024" },
  "/images/moments/golden-beach-cape-town-2024.jpg": { name: "Golden beach", location: "Cape Town 2024" },
  "/images/moments/green-point-stadium-cape-town-2024.jpg": { name: "Green Point stadium", location: "Cape Town 2024" },
  "/images/moments/retro-gas-station-cape-town-2024.jpg": { name: "Retro gas station", location: "Cape Town 2024" },
  "/images/moments/lion-s-head-cape-town-2024.jpg": { name: "Lion's Head", location: "Cape Town 2024" },
  "/images/moments/laundry-day-cape-town-2024.jpg": { name: "Laundry day", location: "Cape Town 2024" },
  "/images/moments/camp-below-the-peak-dolomites-2026.jpg": { name: "Camp below the peak", location: "Dolomites 2026" },
  "/images/moments/alpine-meadow-dolomites-2026.jpg": { name: "Alpine meadow", location: "Dolomites 2026" },
  "/images/moments/bikes-at-lago-di-braies-dolomites-2026.jpg": { name: "Bikes at Lago di Braies", location: "Dolomites 2026" },
  "/images/moments/silhouette-dolomites-2026.jpg": { name: "Silhouette", location: "Dolomites 2026" },
  "/images/moments/loaded-up-dolomites-2026.jpg": { name: "Loaded up", location: "Dolomites 2026" },
  "/images/moments/shadow-self-portrait-dolomites-2026.jpg": { name: "Shadow self-portrait", location: "Dolomites 2026" },
  "/images/moments/house-number-73-cape-town-2026.jpg": { name: "House number 73", location: "Cape Town 2026" },
  "/images/moments/beach-huts-cape-town-2026.jpg": { name: "Beach huts", location: "Cape Town 2026" },
  "/images/moments/wild-camping-dolomites-2026.jpg": { name: "Wild camping", location: "Dolomites 2026" },
  "/images/moments/mountain-marina-lake-garda-2026.jpg": { name: "Mountain marina", location: "Lake Garda 2026" },
  "/images/moments/room-with-a-view-dolomites-2026.jpg": { name: "Room with a view", location: "Dolomites 2026" },
  "/images/moments/lunch-break-dolomites-2026.jpg": { name: "Lunch break", location: "Dolomites 2026" },
  "/images/moments/ponto-final-lisbon-2026.jpg": { name: "Ponto Final", location: "Lisbon 2026" },
  "/images/moments/above-the-valley-dolomites-2026.jpg": { name: "Above the valley", location: "Dolomites 2026" },
  "/images/moments/wildflowers-dolomites-2026.jpg": { name: "Wildflowers", location: "Dolomites 2026" },
  "/images/moments/alpine-cows-dolomites-2026.jpg": { name: "Alpine cows", location: "Dolomites 2026" },
  "/images/moments/alpine-hotel-dolomites-2026.jpg": { name: "Alpine hotel", location: "Dolomites 2026" },
  "/images/moments/dusk-over-the-lake-lake-garda-2026.jpg": { name: "Dusk over the lake", location: "Lake Garda 2026" },
  "/images/moments/which-way-next-dolomites-2026.jpg": { name: "Which way next", location: "Dolomites 2026" },
  "/images/moments/pedal-boats-lake-garda-2026.jpg": { name: "Pedal boats", location: "Lake Garda 2026" },
  "/images/moments/golden-hour-bike-dolomites-2026.jpg": { name: "Golden hour bike", location: "Dolomites 2026" },
  "/images/moments/packed-and-ready-dolomites-2026.jpg": { name: "Packed and ready", location: "Dolomites 2026" },
  "/images/moments/marina-at-sunset-lake-garda-2026.jpg": { name: "Marina at sunset", location: "Lake Garda 2026" },
  "/images/moments/pastel-corner-dolomites-2026.jpg": { name: "Pastel corner", location: "Dolomites 2026" },
  "/images/moments/lakeside-hotel-lake-garda-2026.jpg": { name: "Lakeside hotel", location: "Lake Garda 2026" },
  "/images/moments/below-the-wall-dolomites-2026.jpg": { name: "Below the wall", location: "Dolomites 2026" },
  "/images/moments/view-from-the-tent-dolomites-2026.jpg": { name: "View from the tent", location: "Dolomites 2026" },
  "/images/moments/crossing-the-border-dolomites-2026.jpg": { name: "Crossing the border", location: "Dolomites 2026" },
  "/images/moments/church-in-the-vineyards-italy-2026.jpg": { name: "Church in the vineyards", location: "Italy 2026" },
  "/images/moments/nightfall-on-the-lake-lake-garda-2026.jpg": { name: "Nightfall on the lake", location: "Lake Garda 2026" },
  "/images/moments/lake-ferry-lake-garda-2026.jpg": { name: "Lake ferry", location: "Lake Garda 2026" },
  "/images/moments/chalet-country-alps-2026.jpg": { name: "Chalet country", location: "Alps 2026" },
  "/images/moments/through-the-trees-italy-2026.jpg": { name: "Through the trees", location: "Italy 2026" },
  "/images/moments/glittering-water-lake-garda-2026.jpg": { name: "Glittering water", location: "Lake Garda 2026" },
  "/images/moments/lago-di-braies-dolomites-2026.jpg": { name: "Lago di Braies", location: "Dolomites 2026" },
  "/images/moments/hilltop-church-dolomites-2026.jpg": { name: "Hilltop church", location: "Dolomites 2026" },
  "/images/moments/summer-chairlift-dolomites-2026.jpg": { name: "Summer chairlift", location: "Dolomites 2026" },
  "/images/moments/vintage-caravan-dolomites-2026.jpg": { name: "Vintage caravan", location: "Dolomites 2026" },
  "/images/moments/prinsentuin-leeuwarden-2020.jpg": { name: "Prinsentuin", location: "Leeuwarden 2020" },
  "/images/moments/prinsentuin-leeuwarden-2021.jpg": { name: "Prinsentuin", location: "Leeuwarden 2021" },
  "/images/moments/retro-bike-netherlands-2021.jpg": { name: "Retro bike", location: "Netherlands 2021" },
  "/images/moments/sunset-tower-netherlands-2021.jpg": { name: "Sunset tower", location: "Netherlands 2021" },
  "/images/moments/evening-sky-netherlands-2021.jpg": { name: "Evening sky", location: "Netherlands 2021" },
  "/images/moments/dune-cabin-terschelling-2020.jpg": { name: "Dune cabin", location: "Terschelling 2020" },
  "/images/moments/cycling-the-crete-tuscany-2021.jpg": { name: "Cycling the Crete", location: "Tuscany 2021" },
  "/images/moments/vintage-volvo-netherlands-2020.jpg": { name: "Vintage Volvo", location: "Netherlands 2020" },
  "/images/moments/vintage-volvo-netherlands-2020-2.jpg": { name: "Vintage Volvo", location: "Netherlands 2020" },
  "/images/moments/wadden-at-low-tide-wadden-sea-2021.jpg": { name: "Wadden at low tide", location: "Wadden Sea 2021" },
  "/images/moments/frozen-morning-netherlands-2021.jpg": { name: "Frozen morning", location: "Netherlands 2021" },
  "/images/moments/passo-sella-dolomites-2021.jpg": { name: "Passo Sella", location: "Dolomites 2021" },
  "/images/moments/autumn-in-the-harbour-netherlands-2021.jpg": { name: "Autumn in the harbour", location: "Netherlands 2021" },
  "/images/moments/caught-on-camera-netherlands-2021.jpg": { name: "Caught on camera", location: "Netherlands 2021" },
  "/images/moments/twin-doors-netherlands-2021.jpg": { name: "Twin doors", location: "Netherlands 2021" },
  "/images/moments/beach-post-netherlands-2021.jpg": { name: "Beach post", location: "Netherlands 2021" },
  "/images/moments/mailboxes-in-bloom-netherlands-2021.jpg": { name: "Mailboxes in bloom", location: "Netherlands 2021" },
  "/images/moments/green-jersey-netherlands-2026.jpg": { name: "Green jersey", location: "Netherlands 2026" },
  "/images/moments/polka-dot-jersey-netherlands-2026.jpg": { name: "Polka dot jersey", location: "Netherlands 2026" },
};
